~/.sbsyncmaster/* - add env.source file, tweaks

diff --git a/.sbsyncmaster/sync-and-build b/.sbsyncmaster/sync-and-build
--- a/.sbsyncmaster/sync-and-build
+++ b/.sbsyncmaster/sync-and-build
@@ -1,5 +1,28 @@
 #!/bin/sh
-SMDIR=${HOME}/.sbsyncmaster
-LOGDIR=${SMDIR}/${CLUSTER}.logs
+if ["${SYNCMASTERDIR}"  == ""] ||
+   ["${LATESTPASSDIR}"  == ""] ||
+   ["${GIT_USER_NAME}"  == ""] ||
+   ["${GIT_USER_EMAIL}" == ""] ||
+   ["${CLUSTER}"        == ""]
+then
+    echo
+    echo "One or more required environment symbols is not defined:"
+    echo
+    echo "  SYNCMASTERDIR  = ${SYNCMASTERDIR}"
+    echo "  LATESTPASSDIR  = ${LATESTPASSDIR}"
+    echo "  GIT_USER_NAME  = ${GIT_USER_NAME}"
+    echo "  GIT_USER_EMAIL = ${GIT_USER_EMAIL}"
+    echo "  CLUSTER        = ${CLUSTER}"
+    echo
+    echo "Did you invoke the script manually without providing these symbols?"
+    echo
+    echo "A manual invocation might look like:"
+    echo
+    echo "  CLUSTER=<Bcluster> . ~/.sbsyncmaster/env.source && ~/.sbsyncmaster/sync-and-build"
+    echo
+    exit 1
+fi
 
-nice sbsyncmaster -sbstop -C /ws -r ${CLUSTER} -no-perforce -log-dir ${LOGDIR} -cfg ${SMDIR}/git-enabled-workspace.cfg
+LOGDIR=${SYNCMASTERDIR}/${CLUSTER}.logs
+
+nice sbsyncmaster -sbstop -C ${LATESTPASSDIR} -r ${CLUSTER} -no-perforce -log-dir ${LOGDIR} -cfg ${SYNCMASTERDIR}/git-enabled-workspace.cfg
